--- 
abstract: ~
author: ~
build_requires: 
  Test::Declare: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.680
license: unknown
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Skinny
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0
  Class::Data::Inheritable: 0
  Class::Trigger: 0
  DBI: 0
  Digest::SHA1: 0
  Module::Find: 0
  SQL::Abstract::Limit: 0
  SQL::Parser: 0
  Sub::Install: 0
  UNIVERSAL::require: 0
version: 0.01
